name: msal_auth
description: "A new Flutter plugin for Azure AD authentication."
version: 1.0.2
homepage: https://auberginesolutions.com
repository: https://github.com/nayanAubie/msal_auth
issue_tracker: https://github.com/nayanAubie/msal_auth/issues

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.3

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.example.msal_auth
        pluginClass: MsalAuthPlugin
      ios:
        pluginClass: MsalAuthPlugin
