name: msal_auth
description: "A new Flutter plugin for Azure AD authentication."
version: 1.0.0
homepage: https://auberginesolutions.com
repository: https://github.com/nayanAubie/msal_auth
issue_tracker: https://github.com/fabio21/azure_ad_authentication/issues

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  plugin:
    platforms:
      android:
        package: com.example.msal_auth
        pluginClass: MsalAuthPlugin
      ios:
        pluginClass: MsalAuthPlugin
